[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn study_platform.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
preDeployCommand = ["/opt/venv/bin/python manage.py migrate --noinput && /opt/venv/bin/python manage.py collectstatic --noinput"]
